name: tapioca_v2
description: "Tapioca V2 is a Flutter plugin for video editing on Android and iOS."
version: 1.0.0+2
homepage: https://github.com/thangpn0207/tapioca_v2

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.tapioca_v2.plg.tapioca_v2
        pluginClass: TapiocaV2Plugin
      ios:
        pluginClass: TapiocaV2Plugin